// Code generated by go-swagger; DO NOT EDIT.

package meshes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteMeshParams creates a new DeleteMeshParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteMeshParams() *DeleteMeshParams {
	return &DeleteMeshParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteMeshParamsWithTimeout creates a new DeleteMeshParams object
// with the ability to set a timeout on a request.
func NewDeleteMeshParamsWithTimeout(timeout time.Duration) *DeleteMeshParams {
	return &DeleteMeshParams{
		timeout: timeout,
	}
}

// NewDeleteMeshParamsWithContext creates a new DeleteMeshParams object
// with the ability to set a context for a request.
func NewDeleteMeshParamsWithContext(ctx context.Context) *DeleteMeshParams {
	return &DeleteMeshParams{
		Context: ctx,
	}
}

// NewDeleteMeshParamsWithHTTPClient creates a new DeleteMeshParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteMeshParamsWithHTTPClient(client *http.Client) *DeleteMeshParams {
	return &DeleteMeshParams{
		HTTPClient: client,
	}
}

/* DeleteMeshParams contains all the parameters to send to the API endpoint
   for the delete mesh operation.

   Typically these are written to a http.Request.
*/
type DeleteMeshParams struct {

	/* ID.

	   the id of the mesh to be deleted from the database

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete mesh params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteMeshParams) WithDefaults() *DeleteMeshParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete mesh params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteMeshParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete mesh params
func (o *DeleteMeshParams) WithTimeout(timeout time.Duration) *DeleteMeshParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete mesh params
func (o *DeleteMeshParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete mesh params
func (o *DeleteMeshParams) WithContext(ctx context.Context) *DeleteMeshParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete mesh params
func (o *DeleteMeshParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete mesh params
func (o *DeleteMeshParams) WithHTTPClient(client *http.Client) *DeleteMeshParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete mesh params
func (o *DeleteMeshParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete mesh params
func (o *DeleteMeshParams) WithID(id int64) *DeleteMeshParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete mesh params
func (o *DeleteMeshParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteMeshParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
