// Code generated by go-swagger; DO NOT EDIT.

package meshes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/KrzysztofSieczkiewicz/go-service-template/test-swagger-gen/models"
)

// ListMeshesReader is a Reader for the ListMeshes structure.
type ListMeshesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListMeshesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListMeshesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListMeshesOK creates a ListMeshesOK with default headers values
func NewListMeshesOK() *ListMeshesOK {
	return &ListMeshesOK{}
}

/* ListMeshesOK describes a response with status code 200, with default header values.

ListMeshesOK list meshes o k
*/
type ListMeshesOK struct {
	Payload []*models.Mesh
}

func (o *ListMeshesOK) Error() string {
	return fmt.Sprintf("[GET /meshes][%d] listMeshesOK  %+v", 200, o.Payload)
}
func (o *ListMeshesOK) GetPayload() []*models.Mesh {
	return o.Payload
}

func (o *ListMeshesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
