// Code generated by go-swagger; DO NOT EDIT.

package meshes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new meshes API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for meshes API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteMesh(params *DeleteMeshParams, opts ...ClientOption) (*DeleteMeshCreated, error)

	ListMeshes(params *ListMeshesParams, opts ...ClientOption) (*ListMeshesOK, error)

	PostMeshes(params *PostMeshesParams, opts ...ClientOption) (*PostMeshesOK, error)

	PutMesh(params *PutMeshParams, opts ...ClientOption) (*PutMeshOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  DeleteMesh Returns a 201 message
*/
func (a *Client) DeleteMesh(params *DeleteMeshParams, opts ...ClientOption) (*DeleteMeshCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteMeshParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "deleteMesh",
		Method:             "DELETE",
		PathPattern:        "/meshes/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteMeshReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteMeshCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for deleteMesh: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ListMeshes Returns a list of meshes from the data store
*/
func (a *Client) ListMeshes(params *ListMeshesParams, opts ...ClientOption) (*ListMeshesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListMeshesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "listMeshes",
		Method:             "GET",
		PathPattern:        "/meshes",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ListMeshesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListMeshesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for listMeshes: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PostMeshes Returns a 200 message
*/
func (a *Client) PostMeshes(params *PostMeshesParams, opts ...ClientOption) (*PostMeshesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostMeshesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "postMeshes",
		Method:             "POST",
		PathPattern:        "/meshes",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostMeshesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostMeshesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for postMeshes: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PutMesh Returns a 200 message
*/
func (a *Client) PutMesh(params *PutMeshParams, opts ...ClientOption) (*PutMeshOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPutMeshParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "putMesh",
		Method:             "PUT",
		PathPattern:        "/meshes/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutMeshReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PutMeshOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for putMesh: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
