// Code generated by go-swagger; DO NOT EDIT.

package meshes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostMeshesParams creates a new PostMeshesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostMeshesParams() *PostMeshesParams {
	return &PostMeshesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostMeshesParamsWithTimeout creates a new PostMeshesParams object
// with the ability to set a timeout on a request.
func NewPostMeshesParamsWithTimeout(timeout time.Duration) *PostMeshesParams {
	return &PostMeshesParams{
		timeout: timeout,
	}
}

// NewPostMeshesParamsWithContext creates a new PostMeshesParams object
// with the ability to set a context for a request.
func NewPostMeshesParamsWithContext(ctx context.Context) *PostMeshesParams {
	return &PostMeshesParams{
		Context: ctx,
	}
}

// NewPostMeshesParamsWithHTTPClient creates a new PostMeshesParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostMeshesParamsWithHTTPClient(client *http.Client) *PostMeshesParams {
	return &PostMeshesParams{
		HTTPClient: client,
	}
}

/* PostMeshesParams contains all the parameters to send to the API endpoint
   for the post meshes operation.

   Typically these are written to a http.Request.
*/
type PostMeshesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post meshes params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostMeshesParams) WithDefaults() *PostMeshesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post meshes params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostMeshesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post meshes params
func (o *PostMeshesParams) WithTimeout(timeout time.Duration) *PostMeshesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post meshes params
func (o *PostMeshesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post meshes params
func (o *PostMeshesParams) WithContext(ctx context.Context) *PostMeshesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post meshes params
func (o *PostMeshesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post meshes params
func (o *PostMeshesParams) WithHTTPClient(client *http.Client) *PostMeshesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post meshes params
func (o *PostMeshesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PostMeshesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
