// Code generated by go-swagger; DO NOT EDIT.

package meshes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostMeshesReader is a Reader for the PostMeshes structure.
type PostMeshesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostMeshesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostMeshesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostMeshesOK creates a PostMeshesOK with default headers values
func NewPostMeshesOK() *PostMeshesOK {
	return &PostMeshesOK{}
}

/* PostMeshesOK describes a response with status code 200, with default header values.

PostMeshesOK post meshes o k
*/
type PostMeshesOK struct {
}

func (o *PostMeshesOK) Error() string {
	return fmt.Sprintf("[POST /meshes][%d] postMeshesOK ", 200)
}

func (o *PostMeshesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
