// Code generated by go-swagger; DO NOT EDIT.

package meshes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPutMeshParams creates a new PutMeshParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutMeshParams() *PutMeshParams {
	return &PutMeshParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutMeshParamsWithTimeout creates a new PutMeshParams object
// with the ability to set a timeout on a request.
func NewPutMeshParamsWithTimeout(timeout time.Duration) *PutMeshParams {
	return &PutMeshParams{
		timeout: timeout,
	}
}

// NewPutMeshParamsWithContext creates a new PutMeshParams object
// with the ability to set a context for a request.
func NewPutMeshParamsWithContext(ctx context.Context) *PutMeshParams {
	return &PutMeshParams{
		Context: ctx,
	}
}

// NewPutMeshParamsWithHTTPClient creates a new PutMeshParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutMeshParamsWithHTTPClient(client *http.Client) *PutMeshParams {
	return &PutMeshParams{
		HTTPClient: client,
	}
}

/* PutMeshParams contains all the parameters to send to the API endpoint
   for the put mesh operation.

   Typically these are written to a http.Request.
*/
type PutMeshParams struct {

	/* ID.

	   the id of the mesh to be deleted from the database

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put mesh params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutMeshParams) WithDefaults() *PutMeshParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put mesh params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutMeshParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put mesh params
func (o *PutMeshParams) WithTimeout(timeout time.Duration) *PutMeshParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put mesh params
func (o *PutMeshParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put mesh params
func (o *PutMeshParams) WithContext(ctx context.Context) *PutMeshParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put mesh params
func (o *PutMeshParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put mesh params
func (o *PutMeshParams) WithHTTPClient(client *http.Client) *PutMeshParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put mesh params
func (o *PutMeshParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put mesh params
func (o *PutMeshParams) WithID(id int64) *PutMeshParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put mesh params
func (o *PutMeshParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutMeshParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
