// Code generated by go-swagger; DO NOT EDIT.

package meshes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PutMeshReader is a Reader for the PutMesh structure.
type PutMeshReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutMeshReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutMeshOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutMeshOK creates a PutMeshOK with default headers values
func NewPutMeshOK() *PutMeshOK {
	return &PutMeshOK{}
}

/* PutMeshOK describes a response with status code 200, with default header values.

PutMeshOK put mesh o k
*/
type PutMeshOK struct {
}

func (o *PutMeshOK) Error() string {
	return fmt.Sprintf("[PUT /meshes/{id}][%d] putMeshOK ", 200)
}

func (o *PutMeshOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
